version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/development/Dockerfile
        container_name: testLearn
        ports:
            - "8123:80"
        volumes:
            - ./:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: 'mariadb:10.6.11'
        container_name: testLearn-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - app-network
    phpmyadmin:
          container_name: testLearn-phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - "7000:80"
          links:
            - db:db
          environment:
              - MYSQL_USER= root
              - MYSQL_PASSWORD= s3cre7
              - MYSQL_ROOT_PASSWORD= s3cre7
          networks:
            - app-network

networks:
    app-network:
        driver: bridge
